Server:
  RunMode: debug
  HttpPort: 7500
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExt:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: mysql
  DBName: IvoryDb
  Charset: utf8
  ParseTime: True
  MaxIdleConn: 10
  MaxOpenConn: 30
Redis:
  HttpPort: 6379
Token:
  Secret: AD23EE3feQe21SDX21332CDsa13EF212
  Expire: 86400