definitions:
  domain.User:
    properties:
      account_id:
        type: integer
      address:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  error_code.ErrorData:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  handler.SetUserRequest:
    properties:
      address:
        type: string
      gender:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/account/login:
    post:
      description: Login
      parameters:
      - description: 帳號
        in: formData
        name: account
        required: true
        type: string
      - description: 密碼
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - Account
  /v1/account/register:
    post:
      description: Register
      parameters:
      - description: 帳號
        in: formData
        name: account
        required: true
        type: string
      - description: 密碼
        in: formData
        name: password
        required: true
        type: string
      - description: 信箱
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - Account
  /v1/user:
    post:
      consumes:
      - application/json
      description: Set the user information
      parameters:
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.SetUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error_code.ErrorData'
      summary: Set the user information
      tags:
      - User
  /v1/user/{id}:
    get:
      consumes:
      - application/json
      description: Get User info
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      summary: Get User information by user_id
      tags:
      - User
swagger: "2.0"
