info:
  contact: {}
paths:
  /v1/account/login:
    post:
      description: 取得用戶
      parameters:
      - description: 帳號
        in: formData
        name: account
        required: true
        type: string
      - description: 密碼
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - 取得用戶
  /v1/account/signIn:
    post:
      parameters:
      - description: 帳號
        in: formData
        name: account
        required: true
        type: string
      - description: 密碼
        in: formData
        name: password
        required: true
        type: string
      - description: 信箱
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - 取得用戶
  /v1/user:
    post:
      description: 設定用戶資料
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 性別
        in: formData
        name: gender
        required: true
        type: string
      - description: 姓名
        in: formData
        name: name
        required: true
        type: string
      - description: 地址
        in: formData
        name: address
        required: true
        type: string
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - 取得用戶
  /v1/user/{id}:
    get:
      description: 取得用戶
      responses:
        "200":
          description: code","method","path","id"}
          schema:
            type: string
      tags:
      - 取得用戶
swagger: "2.0"
