name: Run Tests on Develop

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install gomock
        working-directory: gate
        run: go get github.com/golang/mock/gomock@v1.6.0

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: Generate mocks
        working-directory: gate
        run: go generate ./...

      - name: Run tests
        working-directory: gate
        run: go test ./... -v
